# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9681d20676032cbdf78d969bbb9e44459346a91144664722cde5ea4e57bb2fc17e470fa9a53aa3a2f56d8358457ffbbcb9ce87769d2cd727d09aa0c556817488

test:
  secret_key_base: c977081cadf2d298cf21afd9fa48c0485fbaef829fd5a3dd5d10b9f413cf2b045e9f10090734204e245724bcd9f1d01feb16cfde047e223953187e958042818d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
